src/Entity/Result.php
<?php

namespace App\Entity;

use App\Repository\ResultRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ResultRepository::class)]
class Result
{

/* ------------------------------------------------------------- COMPOSANT ------------------------------------------------------------------ */

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'integer')]
    private $grades;

    #[ORM\Column(type: 'datetime')]
    private $update_at;

/* --------------------------------------------------------------- RELATION ----------------------------------------------------------------- */

    #[ORM\ManyToOne(targetEntity: Exercise::class, inversedBy: 'results')]
    #[ORM\JoinColumn(nullable: false)]
    private $exercise;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'results')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

/* ---------------------------------------------------------------- GETTER ------------------------------------------------------------------ */

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGrades(): ?int
    {
        return $this->grades;
    }

    public function getUpdateAt(): ?\DateTime
    {
        return $this->update_at;
    }

/* ---------------------------------------------------------------- SETTER ------------------------------------------------------------------ */

    public function setGrades(int $grades): self
    {
        $this->grades = $grades;

        return $this;
    }

    public function setUpdateAt(\DateTime $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

/* ---------------------------------------------------------- RELATION (EXERCISE) ------------------------------------------------------------ */

    public function getExercise(): ?Exercise
    {
        return $this->exercise;
    }

    public function setExercise(?Exercise $exercise): self
    {
        $this->exercise = $exercise;

        return $this;
    }

/* ------------------------------------------------------------ RELATION (USER) --------------------------------------------------------------- */

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Form/ResultType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Result;
use App\Entity\Exercise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ResultType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('grades')
            ->add('exercise', EntityType::class, [
    
                'label' => 'Exercise',
                'attr' => ['class' => 'form-control'],
                'placeholder' => 'Choisir un exercice',
                'class' => Exercise::class,
                'choice_label' => 'title'
        ])
            ->add('user', EntityType::class, [
    
                'label' => 'User',
                'attr' => ['class' => 'form-control'],
                'placeholder' => 'Choisir un apprenant',
                'class' => User::class,
                'choice_label' => 'name'
        ])
        ;
    }


    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Result::class,
        ]);
    }
}

src/Controller/ResultController.php
<?php

namespace App\Controller;

use App\Entity\Result;
use App\Form\ResultType;
use App\Repository\ResultRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/* ------------------------------------------------------- Route RESULT (Principal) ------------------------------------------------------*/

#[Route('/result', name: 'app_result_')]
class ResultController extends AbstractController
{

/* ---------------------------------------------------------- Route RESULT (Home) --------------------------------------------------------*/

    #[Route('/', name: 'index', methods: ['GET'])]
    public function index(ResultRepository $resultRepository): Response
    {
        // Déclaration de la variable 'average'
        $average = [];
        
    // --------------------------------------------------------------------
        
        // Fonction pour calculer le total des moyennes (moyenne de classe)
        function getAverage(array $average){
            $somme = 0;
            foreach($average as $note){
              $somme =  $somme + $note;
            }
            return $moyenne=($somme / count($average));
        };

    // --------------------------------------------------------------------
        
        // Fonction pour calculer la moyenne de chaque élève (par son ID)
        function getAverageById(array $average){
            $somme = 0;
            $tableau = [];
            // parcourir l'entité + récupération de notes
            foreach($average as $notes){
            array_push($tableau, $notes['grades']);
            }
            // fait la moyenne des notes
            foreach($tableau as $note){
            $somme =  $somme + $note;
            }
            return $moyenne=($somme / count($average));
        };

    //---------------------------------------------------------------------
        
        // Foreach pour aller récupérer toutes les notes pour calculer la moyenne de classe
        foreach($resultRepository->findAll() as $resultEntity) {
            $average[]=$resultEntity->getGrades();
        }
        // Varaible pour calculer le total des moyennes (moyenne de classe)
        //dd(getAverage($average));

    //---------------------------------------------------------------------
        
        // Variable pour calculer la moyenne des apprenants (par ID)
        $ApprenantMoyenne = $resultRepository->findAllinUser(1);
        // Calcul de la moyenne des apprenants
        //dd(getAverageById($ApprenantMoyenne));


        return $this->render('result/index.html.twig', [
            'results' => $resultRepository->findAll(),
        ]);
    }

/* ------------------------------------------------- Route RESULT (Création résultat) ---------------------------------------------------*/

    #[Route('/new', name: 'new', methods: ['GET', 'POST'])]
    public function new(Request $request, ResultRepository $resultRepository): Response
    {
        $result = new Result();
        $form = $this->createForm(ResultType::class, $result);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $result->setUpdateAt(new \DateTime());
            $result->setUser($form->get('user')->getData());
            $result->setExercise($form->get('exercise')->getData());
            $resultRepository->add($result);
            return $this->redirectToRoute('app_result_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('result/new.html.twig', [
            'result' => $result,
            'form' => $form,
        ]);
    }

/* --------------------------------------------------- Route RESULT (Voir résultat) ------------------------------------------------------*/

    #[Route('/{id}', name: 'show', methods: ['GET'])]
    public function show(Result $result): Response
    {
        return $this->render('result/show.html.twig', [
            'result' => $result,
        ]);
    }

/* ------------------------------------------------ Route RESULT (Modifiaction résultat) -------------------------------------------------*/

    #[Route('/{id}/edit', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Result $result, ResultRepository $resultRepository): Response
    {
        $form = $this->createForm(ResultType::class, $result);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $result->setUpdateAt(new \DateTime());
            $resultRepository->add($result);
            return $this->redirectToRoute('app_result_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('result/edit.html.twig', [
            'result' => $result,
            'form' => $form,
        ]);
    }

/* ------------------------------------------------ Route RESULT (Suppression résultat) --------------------------------------------------*/

    #[Route('/{id}', name: 'delete', methods: ['POST'])]
    public function delete(Request $request, Result $result, ResultRepository $resultRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$result->getId(), $request->request->get('_token'))) {
            $resultRepository->remove($result);
        }

        return $this->redirectToRoute('app_result_index', [], Response::HTTP_SEE_OTHER);
    }

}

templates/result/_delete_form.html.twig
<form method="post" action="{{ path('app_result_delete', {'id': result.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ result.id) }}">
    <button class="btn">Supprimer ce résultat</button>
</form>

templates/result/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/result/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Result{% endblock %}

{% block body %}
    <h1>Edit Result</h1>

    {{ include('result/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_result_index') }}" class="btn btn-primary">Retour à l'historique de résultat</a>

    {{ include('result/_delete_form.html.twig') }}
{% endblock %}

templates/result/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Résultat{% endblock %}

{% block body %}
    <h1>Historique de résultats</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Apprenant</th>
                <th>Exercice</th>     
                <th>Notes</th>
                <th>Fait_le</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for result in results %}
            <tr>
                <td>{{ result.user.name }} {{ result.user.firstname }}</td>
                <td>{{ result.exercise.title }}</td>
                <td>{{ result.grades }} / 20</td>
                <td>{{ result.updateAt ? result.updateAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_result_show', {'id': result.id}) }}">Voir</a>
                    <a href="{{ path('app_result_edit', {'id': result.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Rien à été trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_result_new') }}" class="btn btn-primary">Créer un nouveau resultat</a>

            <div>------------------------------------------------------------------------------------------------------------------------------</div>
    {% for result in results %}
    {{ result.grades }}
    {% endfor %}
{% endblock %}

templates/result/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création d'un résultat{% endblock %}

{% block body %}
    <h1>Création d'un nouveau resultat</h1>

    {{ include('result/_form.html.twig') }}

    <a href="{{ path('app_result_index') }}" class="btn btn-primary">Retour à l'historique de résultat</a>
{% endblock %}

templates/result/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Resultat{% endblock %}

{% block body %}
    <h1>Resultat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Apprenant</th>
                <td>{{ result.user.name }} {{ result.user.firstname }}</td>
            </tr>
            <tr>
                <th>Exercice</th>
                <td>{{ result.exercise.title }}</td>
            </tr>
            <tr>
                <th>Notes</th>
                <td>{{ result.grades }} / 20 </td>
            </tr>
            <tr>
                <th>Fait_le</th>
                <td>{{ result.updateAt ? result.updateAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_result_index') }}" class="btn btn-primary">Retour à la liste de résultat</a>

    <a href="{{ path('app_result_edit', {'id': result.id}) }}" class="btn btn-primary">Modifier</a>

    {{ include('result/_delete_form.html.twig') }}
{% endblock %}